default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.3'
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        pass_filenames: false
        require_serial: true
        types: [python]
        entry: poetry run mypy -v -p src
        args:
          - --install-types
          - --non-interactive
          - --strict
          - --show-error-codes