version: '3.5'
services:
  arch_api:
    image: europe-west1-docker.pkg.dev/arch-api-403919/arch-api-registry/arch-api:main
    restart: always
    ports:
      - "80:8000"
    networks:
      - arch-api
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
  mongo:
    image: mongo
    restart: always
    networks:
      - arch-api
    volumes:
      - "./data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  arch-api:
    name: arch-api
