version: '3.5'
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - arch-api
    volumes:
      - "./data/db:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  arch-api:
    name: arch-api
