name: Build
on:
  pull_request:
    branches:
      - main
      - 'releases/**'

env:
  PYTHON_VERSION: '3.11'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # Dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry
          poetry config virtualenvs.create false
          poetry install
      # Linting
      - name: Linting and static code checks
        run: |
          pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URL: "mongodb://root:example@0.0.0.0:27017/"

    services:
      # setup mongodb
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        # Expose ports
        ports:
          - "27017:27017"

    steps:
      # Checkout
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # Dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry
          poetry config virtualenvs.create false
          poetry install
      # Tests
      - name: Test
        run: poetry run pytest .
