name: Deploy Docker image to Google Artifact Registry
on:
  push:
    branches:
      - main
      - docker_deploy # TODO remove
      - 'releases/**'
jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: 'actions/checkout@v3'
      # Login to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          token_format: 'access_token'
          access_token_lifetime: '300s' # optional, default: '3600s' (1 hour)
      # Login to Artifact Registry
      - uses: 'docker/login-action@v1'
        with:
          registry: 'europe-west1-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://europe-west1-docker.pkg.dev

      - run: echo "yayy 🎉"
